/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Desktop;
import java.net.URL;
import javax.swing.JOptionPane;
/**
 *
 * @author HawkZ
 */
public class HeritageSite extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public HeritageSite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hertSitesLbl1 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        swayambhuBtns1 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        lumbiniBtns1 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        pashupathiBtns1 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        kathDurbarLbl1 = new javax.swing.JLabel();
        swayambhuLbl1 = new javax.swing.JLabel();
        lumbiniLbl1 = new javax.swing.JLabel();
        pashupathiLbl1 = new javax.swing.JLabel();
        pashuImgLbl1 = new javax.swing.JLabel();
        kathImgLbl2 = new javax.swing.JLabel();
        syambhuImgLbl2 = new javax.swing.JLabel();
        lumbiniImgLbl2 = new javax.swing.JLabel();
        kathmanduBtns1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        btmPannel = new javax.swing.JPanel();
        sagarmathaBtns = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        boudhaBtns = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ptnDurBtns = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        bhaktBtns = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        sagarmathaLbl = new javax.swing.JLabel();
        boudhanathLbl = new javax.swing.JLabel();
        ptnDurbarLbl = new javax.swing.JLabel();
        bhktLbl = new javax.swing.JLabel();
        bhtkDurImgLbl = new javax.swing.JLabel();
        sagarmathaImgLbl = new javax.swing.JLabel();
        boudhaImgLbl = new javax.swing.JLabel();
        ptnDurImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        hertSitesLbl1.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 18)); // NOI18N
        hertSitesLbl1.setText("Heritage Sites");

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(null);

        swayambhuBtns1.setBackground(new java.awt.Color(255, 255, 255));
        swayambhuBtns1.setRequestFocusEnabled(false);
        swayambhuBtns1.setLayout(null);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton16.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        swayambhuBtns1.add(jButton16);
        jButton16.setBounds(70, 0, 28, 27);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton18.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        swayambhuBtns1.add(jButton18);
        jButton18.setBounds(40, 0, 28, 27);

        topPanel.add(swayambhuBtns1);
        swayambhuBtns1.setBounds(190, 220, 130, 27);

        lumbiniBtns1.setBackground(new java.awt.Color(255, 255, 255));
        lumbiniBtns1.setRequestFocusEnabled(false);
        lumbiniBtns1.setLayout(null);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton19.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        lumbiniBtns1.add(jButton19);
        jButton19.setBounds(70, 0, 28, 27);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton21.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        lumbiniBtns1.add(jButton21);
        jButton21.setBounds(40, 0, 28, 27);

        topPanel.add(lumbiniBtns1);
        lumbiniBtns1.setBounds(370, 220, 130, 27);

        pashupathiBtns1.setBackground(new java.awt.Color(255, 255, 255));
        pashupathiBtns1.setRequestFocusEnabled(false);
        pashupathiBtns1.setLayout(null);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton22.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        pashupathiBtns1.add(jButton22);
        jButton22.setBounds(70, 0, 28, 27);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton24.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        pashupathiBtns1.add(jButton24);
        jButton24.setBounds(40, 0, 28, 27);

        topPanel.add(pashupathiBtns1);
        pashupathiBtns1.setBounds(540, 220, 130, 27);

        kathDurbarLbl1.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        kathDurbarLbl1.setText("Kathmandu Durbar Square");
        kathDurbarLbl1.setMaximumSize(new java.awt.Dimension(130, 14));
        kathDurbarLbl1.setMinimumSize(new java.awt.Dimension(130, 14));
        kathDurbarLbl1.setPreferredSize(new java.awt.Dimension(140, 14));
        topPanel.add(kathDurbarLbl1);
        kathDurbarLbl1.setBounds(10, 10, 140, 14);

        swayambhuLbl1.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        swayambhuLbl1.setText("Swayambhunath Stupa");
        swayambhuLbl1.setMaximumSize(new java.awt.Dimension(125, 14));
        swayambhuLbl1.setMinimumSize(new java.awt.Dimension(125, 14));
        swayambhuLbl1.setPreferredSize(new java.awt.Dimension(140, 14));
        topPanel.add(swayambhuLbl1);
        swayambhuLbl1.setBounds(190, 10, 140, 14);

        lumbiniLbl1.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        lumbiniLbl1.setText("Lumbini");
        lumbiniLbl1.setMaximumSize(new java.awt.Dimension(125, 14));
        lumbiniLbl1.setMinimumSize(new java.awt.Dimension(125, 14));
        lumbiniLbl1.setPreferredSize(new java.awt.Dimension(140, 14));
        topPanel.add(lumbiniLbl1);
        lumbiniLbl1.setBounds(370, 10, 140, 14);

        pashupathiLbl1.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        pashupathiLbl1.setText("Pashupatinath Temple");
        pashupathiLbl1.setMaximumSize(new java.awt.Dimension(125, 14));
        pashupathiLbl1.setMinimumSize(new java.awt.Dimension(125, 14));
        pashupathiLbl1.setPreferredSize(new java.awt.Dimension(140, 14));
        topPanel.add(pashupathiLbl1);
        pashupathiLbl1.setBounds(540, 10, 140, 14);

        pashuImgLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pashuImgLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pashupathinath-temple.jpg"))); // NOI18N
        pashuImgLbl1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pashuImgLbl1.setPreferredSize(new java.awt.Dimension(140, 190));
        topPanel.add(pashuImgLbl1);
        pashuImgLbl1.setBounds(540, 30, 140, 180);

        kathImgLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kathImgLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Kathmandu-Durbar-Square.jpg"))); // NOI18N
        kathImgLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kathImgLbl2.setPreferredSize(new java.awt.Dimension(140, 190));
        topPanel.add(kathImgLbl2);
        kathImgLbl2.setBounds(10, 30, 140, 180);

        syambhuImgLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        syambhuImgLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Swayambhunath-Stupa.jpg"))); // NOI18N
        syambhuImgLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        syambhuImgLbl2.setPreferredSize(new java.awt.Dimension(140, 190));
        topPanel.add(syambhuImgLbl2);
        syambhuImgLbl2.setBounds(190, 30, 140, 180);

        lumbiniImgLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lumbiniImgLbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lumbini.jpg"))); // NOI18N
        lumbiniImgLbl2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lumbiniImgLbl2.setPreferredSize(new java.awt.Dimension(140, 190));
        topPanel.add(lumbiniImgLbl2);
        lumbiniImgLbl2.setBounds(370, 30, 140, 180);

        kathmanduBtns1.setBackground(new java.awt.Color(255, 255, 255));
        kathmanduBtns1.setRequestFocusEnabled(false);
        kathmanduBtns1.setLayout(null);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton13.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        kathmanduBtns1.add(jButton13);
        jButton13.setBounds(60, 0, 28, 27);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton15.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        kathmanduBtns1.add(jButton15);
        jButton15.setBounds(40, 0, 20, 27);

        topPanel.add(kathmanduBtns1);
        kathmanduBtns1.setBounds(10, 220, 130, 27);

        btmPannel.setBackground(new java.awt.Color(255, 255, 255));
        btmPannel.setLayout(null);

        sagarmathaBtns.setBackground(new java.awt.Color(255, 255, 255));
        sagarmathaBtns.setRequestFocusEnabled(false);
        sagarmathaBtns.setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        sagarmathaBtns.add(jButton3);
        jButton3.setBounds(70, 0, 28, 27);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sagarmathaBtns.add(jButton1);
        jButton1.setBounds(40, 0, 28, 27);

        btmPannel.add(sagarmathaBtns);
        sagarmathaBtns.setBounds(10, 220, 130, 27);

        boudhaBtns.setBackground(new java.awt.Color(255, 255, 255));
        boudhaBtns.setRequestFocusEnabled(false);
        boudhaBtns.setLayout(null);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        boudhaBtns.add(jButton4);
        jButton4.setBounds(70, 0, 28, 27);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton6.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        boudhaBtns.add(jButton6);
        jButton6.setBounds(40, 0, 28, 27);

        btmPannel.add(boudhaBtns);
        boudhaBtns.setBounds(191, 220, 130, 27);

        ptnDurBtns.setBackground(new java.awt.Color(255, 255, 255));
        ptnDurBtns.setRequestFocusEnabled(false);
        ptnDurBtns.setLayout(null);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton7.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        ptnDurBtns.add(jButton7);
        jButton7.setBounds(70, 0, 28, 27);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        ptnDurBtns.add(jButton9);
        jButton9.setBounds(40, 0, 28, 27);

        btmPannel.add(ptnDurBtns);
        ptnDurBtns.setBounds(372, 220, 130, 27);

        bhaktBtns.setBackground(new java.awt.Color(255, 255, 255));
        bhaktBtns.setRequestFocusEnabled(false);
        bhaktBtns.setLayout(null);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/description.png"))); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        bhaktBtns.add(jButton10);
        jButton10.setBounds(60, 0, 28, 27);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        jButton12.setPreferredSize(new java.awt.Dimension(28, 27));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        bhaktBtns.add(jButton12);
        jButton12.setBounds(30, 0, 28, 27);

        btmPannel.add(bhaktBtns);
        bhaktBtns.setBounds(553, 220, 130, 27);

        sagarmathaLbl.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        sagarmathaLbl.setText("Sagarmatha National Park");
        sagarmathaLbl.setMaximumSize(new java.awt.Dimension(130, 14));
        sagarmathaLbl.setMinimumSize(new java.awt.Dimension(130, 14));
        sagarmathaLbl.setPreferredSize(new java.awt.Dimension(140, 14));
        btmPannel.add(sagarmathaLbl);
        sagarmathaLbl.setBounds(10, 10, 140, 14);

        boudhanathLbl.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        boudhanathLbl.setText("Boudhanath Stupa");
        boudhanathLbl.setMaximumSize(new java.awt.Dimension(125, 14));
        boudhanathLbl.setMinimumSize(new java.awt.Dimension(125, 14));
        boudhanathLbl.setPreferredSize(new java.awt.Dimension(140, 14));
        btmPannel.add(boudhanathLbl);
        boudhanathLbl.setBounds(190, 10, 140, 14);

        ptnDurbarLbl.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        ptnDurbarLbl.setText("Patan Durbar Square");
        ptnDurbarLbl.setMaximumSize(new java.awt.Dimension(125, 14));
        ptnDurbarLbl.setMinimumSize(new java.awt.Dimension(125, 14));
        ptnDurbarLbl.setPreferredSize(new java.awt.Dimension(140, 14));
        btmPannel.add(ptnDurbarLbl);
        ptnDurbarLbl.setBounds(370, 10, 140, 14);

        bhktLbl.setFont(new java.awt.Font("Helvetica LT Condensed", 0, 11)); // NOI18N
        bhktLbl.setText("Bhaktapur Durbar Square");
        bhktLbl.setMaximumSize(new java.awt.Dimension(125, 14));
        bhktLbl.setMinimumSize(new java.awt.Dimension(125, 14));
        bhktLbl.setPreferredSize(new java.awt.Dimension(140, 14));
        btmPannel.add(bhktLbl);
        bhktLbl.setBounds(550, 10, 140, 14);

        bhtkDurImgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bhtkDurImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bhaktapur-durbar-square.jpeg"))); // NOI18N
        bhtkDurImgLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bhtkDurImgLbl.setPreferredSize(new java.awt.Dimension(140, 190));
        btmPannel.add(bhtkDurImgLbl);
        bhtkDurImgLbl.setBounds(550, 30, 140, 180);

        sagarmathaImgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sagarmathaImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sagarmatha-national-park.jpg"))); // NOI18N
        sagarmathaImgLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sagarmathaImgLbl.setPreferredSize(new java.awt.Dimension(140, 190));
        btmPannel.add(sagarmathaImgLbl);
        sagarmathaImgLbl.setBounds(10, 40, 140, 180);

        boudhaImgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boudhaImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/boudhanath-stupa.jpg"))); // NOI18N
        boudhaImgLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boudhaImgLbl.setPreferredSize(new java.awt.Dimension(140, 190));
        btmPannel.add(boudhaImgLbl);
        boudhaImgLbl.setBounds(190, 30, 140, 180);

        ptnDurImgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ptnDurImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patan-durbar-square.jpg"))); // NOI18N
        ptnDurImgLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ptnDurImgLbl.setPreferredSize(new java.awt.Dimension(140, 190));
        btmPannel.add(ptnDurImgLbl);
        ptnDurImgLbl.setBounds(370, 30, 140, 180);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hertSitesLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(hertSitesLbl1)
                .addGap(18, 18, 18)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btmPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Sagarmatha+National+Park/@27.9324234,86.6992007,17z/data=!3m1!4b1!4m5!3m4!1s0x39e854b9e858ff5b:0xa79466607d8747be!8m2!3d27.9324234!4d86.7013894").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Sagarmatha is an exceptional area with dramatic mountains, glaciers and deep valleys, dominated by Mount Everest, the highest peak in the world (8,848 m). Several rare species, such as the snow leopard and the lesser panda, are found in the park.", "Description", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Boudha stupa is semicircle shaped and contains the relics and remains of Buddha. The stupa's massive mandala makes it one of the largest spherical stupas in the world.", "Description", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Boudha+Stupa/@27.7215062,85.3619974,17z/data=!4m12!1m6!3m5!1s0x39eb1bda4a951f0f:0x3ddabb234891c3bd!2sBoudha+Stupa!8m2!3d27.7215062!4d85.3619974!3m4!1s0x39eb1bda4a951f0f:0x3ddabb234891c3bd!8m2!3d27.7215062!4d85.3619974").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Patan Durbar Square is situated at the centre of the city of Lalitpur in Nepal.One of its attractions is the ancient royal palace where the Malla Kings of Lalitpur resided.", "Description", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Patan+Durbar+Square/@27.6726981,85.3231324,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb19c50daa2fb1:0x6f197fa38097b530!8m2!3d27.6726981!4d85.3253211").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bhaktapur Durbar Square is a museum of medieval art and architecture with many examples of sculpture, woodcarving and colossal pagoda temples consecrated to different gods and goddesses which is 15 km far from Kathmandu.", "Description", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Bhaktapur+Durbar+Square/@27.6720744,85.4259136,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb1aafec32df31:0xdda339e731af9bfd!8m2!3d27.6720744!4d85.4281023").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Durbar Square is an important site for Buddhist and Hindu rituals, holy ceremonies, royal events, and kingly coronations.", "Description", JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Kathmandu+Durbar+Square/@27.7041718,85.3044636,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb1857d1f77871:0xc5b0391005a641fd!8m2!3d27.7041729!4d85.306646").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "Swayambhu is an ancient religious complex atop a hill in the Kathmandu Valley, west of Kathmandu city", "Description", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Swayambhu+Mahachaitya+Stupa/@27.7149298,85.2881456,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb188d9b82c8ad:0xae31bde410797bf7!8m2!3d27.7149298!4d85.2903343").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    JOptionPane.showMessageDialog(null, "It is the main temple at Lumbini, a site traditionally considered the birthplace of Gautama Buddha. The temple stands adjacent to a sacred pool (known as Puskarni) and a sacred garden.", "Description", JOptionPane.PLAIN_MESSAGE);                            
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Maya+Devi+Temple/@27.4696415,83.2735961,17z/data=!3m1!4b1!4m5!3m4!1s0x399693610a88a989:0xafbf6e3b743d1e06!8m2!3d27.4696415!4d83.2757848").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
            JOptionPane.showMessageDialog(null, "This extensive Hindu temple precinct is a sprawling collection of temples, ashrams, images and inscriptions raised over the centuries along the banks of the sacred Bagmati river", "Description", JOptionPane.PLAIN_MESSAGE);                            

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
         try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Pashupatinath+Temple/@27.7104461,85.3465028,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb191aaaaaaaab:0x424c7d0a60df9091!8m2!3d27.7104461!4d85.3486915").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeritageSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeritageSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeritageSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeritageSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeritageSite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bhaktBtns;
    private javax.swing.JLabel bhktLbl;
    private javax.swing.JLabel bhtkDurImgLbl;
    private javax.swing.JPanel boudhaBtns;
    private javax.swing.JLabel boudhaImgLbl;
    private javax.swing.JLabel boudhanathLbl;
    private javax.swing.JPanel btmPannel;
    private javax.swing.JLabel hertSitesLbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kathDurbarLbl1;
    private javax.swing.JLabel kathImgLbl2;
    private javax.swing.JPanel kathmanduBtns1;
    private javax.swing.JPanel lumbiniBtns1;
    private javax.swing.JLabel lumbiniImgLbl2;
    private javax.swing.JLabel lumbiniLbl1;
    private javax.swing.JLabel pashuImgLbl1;
    private javax.swing.JPanel pashupathiBtns1;
    private javax.swing.JLabel pashupathiLbl1;
    private javax.swing.JPanel ptnDurBtns;
    private javax.swing.JLabel ptnDurImgLbl;
    private javax.swing.JLabel ptnDurbarLbl;
    private javax.swing.JPanel sagarmathaBtns;
    private javax.swing.JLabel sagarmathaImgLbl;
    private javax.swing.JLabel sagarmathaLbl;
    private javax.swing.JPanel swayambhuBtns1;
    private javax.swing.JLabel swayambhuLbl1;
    private javax.swing.JLabel syambhuImgLbl2;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
