/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author pradh
 */
public class Home extends javax.swing.JInternalFrame {

    /**
     * Creates new form EverythingLatest
     */
    public Home() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null); 
        getContentPane().setBackground(Color.white);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel494 = new javax.swing.JLabel();
        jLabel495 = new javax.swing.JLabel();
        jLabel496 = new javax.swing.JLabel();
        panel_lod = new javax.swing.JPanel();
        img_boutique2 = new javax.swing.JLabel();
        contact_lod = new javax.swing.JButton();
        directions_lod = new javax.swing.JButton();
        panel_platinum = new javax.swing.JPanel();
        img_annapurna1 = new javax.swing.JLabel();
        directions_platinum = new javax.swing.JButton();
        contact_platinum = new javax.swing.JButton();
        panel_marriott1 = new javax.swing.JPanel();
        img_mariott1 = new javax.swing.JLabel();
        directions_marriott1 = new javax.swing.JButton();
        contact_mariott = new javax.swing.JButton();
        save_Mariott = new javax.swing.JButton();
        panel_shanker2 = new javax.swing.JPanel();
        img_shanker2 = new javax.swing.JLabel();
        contact_shanker2 = new javax.swing.JButton();
        directions_shanker2 = new javax.swing.JButton();
        save_Shanker = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel494.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/world-wide-web (1).png"))); // NOI18N

        jLabel495.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/google-maps.png"))); // NOI18N

        jLabel496.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map (1).png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        panel_lod.setBackground(new java.awt.Color(255, 245, 238));
        panel_lod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LORD OF THE DRINKS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_boutique2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/l_o_d.jpg"))); // NOI18N
        img_boutique2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contact_lod.setBackground(new java.awt.Color(255, 255, 255));
        contact_lod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_lod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_lod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_lodcontact_boutiqueActionPerformed(evt);
            }
        });

        directions_lod.setBackground(new java.awt.Color(255, 255, 255));
        directions_lod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_lod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_lod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_lodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_lodLayout = new javax.swing.GroupLayout(panel_lod);
        panel_lod.setLayout(panel_lodLayout);
        panel_lodLayout.setHorizontalGroup(
            panel_lodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_lodLayout.createSequentialGroup()
                .addComponent(directions_lod)
                .addGap(37, 37, 37)
                .addComponent(contact_lod)
                .addGap(204, 204, 204))
            .addComponent(img_boutique2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panel_lodLayout.setVerticalGroup(
            panel_lodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lodLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_boutique2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_lodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_lodLayout.createSequentialGroup()
                        .addComponent(directions_lod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(panel_lodLayout.createSequentialGroup()
                        .addComponent(contact_lod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panel_platinum.setBackground(new java.awt.Color(255, 245, 238));
        panel_platinum.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLUB PLATINUM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_annapurna1.setBackground(new java.awt.Color(255, 245, 238));
        img_annapurna1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/platinum_.jpg"))); // NOI18N
        img_annapurna1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        directions_platinum.setBackground(new java.awt.Color(255, 255, 255));
        directions_platinum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_platinum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_platinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_platinumActionPerformed(evt);
            }
        });

        contact_platinum.setBackground(new java.awt.Color(255, 255, 255));
        contact_platinum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_platinum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_platinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_platinumcontact_boutiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_platinumLayout = new javax.swing.GroupLayout(panel_platinum);
        panel_platinum.setLayout(panel_platinumLayout);
        panel_platinumLayout.setHorizontalGroup(
            panel_platinumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_platinumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(directions_platinum)
                .addGap(32, 32, 32)
                .addComponent(contact_platinum)
                .addGap(212, 212, 212))
            .addGroup(panel_platinumLayout.createSequentialGroup()
                .addComponent(img_annapurna1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_platinumLayout.setVerticalGroup(
            panel_platinumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_platinumLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(img_annapurna1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_platinumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directions_platinum)
                    .addComponent(contact_platinum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_marriott1.setBackground(new java.awt.Color(255, 245, 238));
        panel_marriott1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KATHMANDU MARIOTT HOTEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_mariott1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/marriott_ext.jpg"))); // NOI18N
        img_mariott1.setText("jLabel1");
        img_mariott1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        directions_marriott1.setBackground(new java.awt.Color(255, 255, 255));
        directions_marriott1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_marriott1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_marriott1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_marriott1ActionPerformed(evt);
            }
        });

        contact_mariott.setBackground(new java.awt.Color(255, 255, 255));
        contact_mariott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_mariott.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_mariott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_mariottcontact_boutiqueActionPerformed(evt);
            }
        });

        save_Mariott.setBackground(new java.awt.Color(255, 255, 255));
        save_Mariott.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/savee.png"))); // NOI18N
        save_Mariott.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Mariott.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_MariottActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_marriott1Layout = new javax.swing.GroupLayout(panel_marriott1);
        panel_marriott1.setLayout(panel_marriott1Layout);
        panel_marriott1Layout.setHorizontalGroup(
            panel_marriott1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_marriott1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(directions_marriott1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(contact_mariott, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(save_Mariott, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(panel_marriott1Layout.createSequentialGroup()
                .addComponent(img_mariott1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_marriott1Layout.setVerticalGroup(
            panel_marriott1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_marriott1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_mariott1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_marriott1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directions_marriott1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contact_mariott, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save_Mariott, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_shanker2.setBackground(new java.awt.Color(255, 245, 238));
        panel_shanker2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HOTEL SHANKER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_shanker2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hotelshanker.jpg"))); // NOI18N
        img_shanker2.setText("jLabel3");
        img_shanker2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contact_shanker2.setBackground(new java.awt.Color(255, 255, 255));
        contact_shanker2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_shanker2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_shanker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_shanker2ActionPerformed(evt);
            }
        });

        directions_shanker2.setBackground(new java.awt.Color(255, 255, 255));
        directions_shanker2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_shanker2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_shanker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_shanker2ActionPerformed(evt);
            }
        });

        save_Shanker.setBackground(new java.awt.Color(255, 255, 255));
        save_Shanker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/savee.png"))); // NOI18N
        save_Shanker.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save_Shanker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_ShankerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_shanker2Layout = new javax.swing.GroupLayout(panel_shanker2);
        panel_shanker2.setLayout(panel_shanker2Layout);
        panel_shanker2Layout.setHorizontalGroup(
            panel_shanker2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_shanker2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(directions_shanker2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contact_shanker2)
                .addGap(118, 118, 118)
                .addComponent(save_Shanker)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_shanker2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(img_shanker2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        panel_shanker2Layout.setVerticalGroup(
            panel_shanker2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_shanker2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_shanker2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_shanker2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contact_shanker2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(save_Shanker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directions_shanker2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel9.setText("Trending Places ");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setText("Trending Places ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_marriott1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panel_shanker2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_lod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panel_platinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(270, 270, 270))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(562, 562, 562)
                    .addComponent(jLabel10)
                    .addContainerGap(565, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_platinum, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_lod, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_marriott1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_shanker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(466, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(535, 535, 535)
                    .addComponent(jLabel10)
                    .addContainerGap(535, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contact_lodcontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_lodcontact_boutiqueActionPerformed
        new LodDetails().setVisible(true);
    }//GEN-LAST:event_contact_lodcontact_boutiqueActionPerformed

    private void directions_lodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_lodActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/27.7179392,85.3446312/kathmandu+boutique+hotel/@27.7127867,85.3086803,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb18fbf85b5015:0x67b5d6aa5fd77def!2m2!1d85.3079041!2d27.7101891").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_lodActionPerformed

    private void directions_platinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_platinumActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//Club+Platinum,+Teendhara+Marg,+Kathmandu+44600/@27.7096768,85.3167578,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x39eb19f5904ae5c3:0x106efc1a81bf9353!2m2!1d85.3189507!2d27.7098354").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_platinumActionPerformed

    private void contact_platinumcontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_platinumcontact_boutiqueActionPerformed
        new PlatinumDetails().setVisible(true);
    }//GEN-LAST:event_contact_platinumcontact_boutiqueActionPerformed

    private void directions_marriott1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_marriott1ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://google.com/maps/dir/27.7179392,85.3446312/marriott+kathmandu/@27.7150685,85.3255871,15z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb190f430461db:0x9bf0669a1f62b934!2m2!1d85.3239387!2d27.7130926?hl=en").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_marriott1ActionPerformed

    private void contact_mariottcontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_mariottcontact_boutiqueActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.marriott.com/hotels/travel/ktmmc-kathmandu-marriott-hotel/").toURI());
        }
          catch(Exception e){}

    }//GEN-LAST:event_contact_mariottcontact_boutiqueActionPerformed

    private void save_MariottActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_MariottActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_MariottActionPerformed

    private void contact_shanker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_shanker2ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.shankerhotel.com.np/contact-page").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_contact_shanker2ActionPerformed

    private void directions_shanker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_shanker2ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/27.7179392,85.3446312/Hotel+Shanker+Kathmandu,+Kathmandu/@27.7193521,85.3221907,15z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb191b68aa7bc3:0x295bea250f832f8d!2m2!1d85.3194684!2d27.7188945").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_shanker2ActionPerformed

    private void save_ShankerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_ShankerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_save_ShankerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contact_lod;
    private javax.swing.JButton contact_mariott;
    private javax.swing.JButton contact_platinum;
    private javax.swing.JButton contact_shanker2;
    private javax.swing.JButton directions_lod;
    private javax.swing.JButton directions_marriott1;
    private javax.swing.JButton directions_platinum;
    private javax.swing.JButton directions_shanker2;
    private javax.swing.JLabel img_annapurna1;
    private javax.swing.JLabel img_boutique2;
    private javax.swing.JLabel img_mariott1;
    private javax.swing.JLabel img_shanker2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel494;
    private javax.swing.JLabel jLabel495;
    private javax.swing.JLabel jLabel496;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_lod;
    private javax.swing.JPanel panel_marriott1;
    private javax.swing.JPanel panel_platinum;
    private javax.swing.JPanel panel_shanker2;
    private javax.swing.JButton save_Mariott;
    private javax.swing.JButton save_Shanker;
    // End of variables declaration//GEN-END:variables
}
