/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author pradh
 */
public class Hotel extends javax.swing.JInternalFrame {

    /**
     * Creates new form EverythingLatest
     */
    public Hotel() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null); 
        getContentPane().setBackground(Color.white);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel_annapurna = new javax.swing.JPanel();
        img_mariott1 = new javax.swing.JLabel();
        directions_annapurna = new javax.swing.JButton();
        contact_annapurna = new javax.swing.JButton();
        panel_dwarika = new javax.swing.JPanel();
        img_boutique1 = new javax.swing.JLabel();
        contact_dwarika = new javax.swing.JButton();
        directions_dwarika = new javax.swing.JButton();
        panel_gokarna = new javax.swing.JPanel();
        img_mulberry2 = new javax.swing.JLabel();
        contact_gokarna = new javax.swing.JButton();
        directions_gokarna = new javax.swing.JButton();
        panel_nepalaya = new javax.swing.JPanel();
        contact_nepalaya = new javax.swing.JButton();
        directions_nepalaya = new javax.swing.JButton();
        img_shanker2 = new javax.swing.JLabel();
        OtherHotel = new javax.swing.JButton();
        panel_haze = new javax.swing.JPanel();
        img_annapurna = new javax.swing.JLabel();
        directions_haze = new javax.swing.JButton();
        contact_haze = new javax.swing.JButton();
        panel_irish2 = new javax.swing.JPanel();
        img_annapurna4 = new javax.swing.JLabel();
        directions_irish2 = new javax.swing.JButton();
        contact_irish2 = new javax.swing.JButton();
        OtherNightlife = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panel_annapurna.setBackground(new java.awt.Color(255, 255, 255));
        panel_annapurna.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HOTEL ANNAPURNA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N
        panel_annapurna.setAutoscrolls(true);

        img_mariott1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_mariott1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/annapurna.png"))); // NOI18N

        directions_annapurna.setBackground(new java.awt.Color(255, 255, 255));
        directions_annapurna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        directions_annapurna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_annapurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_annapurnaActionPerformed(evt);
            }
        });

        contact_annapurna.setBackground(new java.awt.Color(255, 255, 255));
        contact_annapurna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/call.png"))); // NOI18N
        contact_annapurna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_annapurna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_annapurnacontact_boutiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_annapurnaLayout = new javax.swing.GroupLayout(panel_annapurna);
        panel_annapurna.setLayout(panel_annapurnaLayout);
        panel_annapurnaLayout.setHorizontalGroup(
            panel_annapurnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_annapurnaLayout.createSequentialGroup()
                .addGroup(panel_annapurnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_annapurnaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(directions_annapurna)
                        .addGap(49, 49, 49)
                        .addComponent(contact_annapurna)
                        .addGap(0, 100, Short.MAX_VALUE))
                    .addComponent(img_mariott1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        panel_annapurnaLayout.setVerticalGroup(
            panel_annapurnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_annapurnaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_mariott1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_annapurnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact_annapurna)
                    .addComponent(directions_annapurna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_dwarika.setBackground(new java.awt.Color(255, 255, 255));
        panel_dwarika.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THE DWARIKA'S HOTEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_boutique1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_boutique1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dwarika.jpg"))); // NOI18N

        contact_dwarika.setBackground(new java.awt.Color(255, 255, 255));
        contact_dwarika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/call.png"))); // NOI18N
        contact_dwarika.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_dwarika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_dwarikacontact_boutiqueActionPerformed(evt);
            }
        });

        directions_dwarika.setBackground(new java.awt.Color(255, 255, 255));
        directions_dwarika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        directions_dwarika.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_dwarika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_dwarikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dwarikaLayout = new javax.swing.GroupLayout(panel_dwarika);
        panel_dwarika.setLayout(panel_dwarikaLayout);
        panel_dwarikaLayout.setHorizontalGroup(
            panel_dwarikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dwarikaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(directions_dwarika)
                .addGap(18, 18, 18)
                .addComponent(contact_dwarika)
                .addGap(90, 90, 90))
            .addGroup(panel_dwarikaLayout.createSequentialGroup()
                .addComponent(img_boutique1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        panel_dwarikaLayout.setVerticalGroup(
            panel_dwarikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dwarikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_boutique1)
                .addGap(18, 18, 18)
                .addGroup(panel_dwarikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directions_dwarika)
                    .addComponent(contact_dwarika))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_gokarna.setBackground(new java.awt.Color(255, 255, 255));
        panel_gokarna.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GOKARNA FOREST RESORT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_mulberry2.setBackground(new java.awt.Color(255, 255, 255));
        img_mulberry2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_mulberry2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gokarna.jpg"))); // NOI18N

        contact_gokarna.setBackground(new java.awt.Color(255, 255, 255));
        contact_gokarna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/call.png"))); // NOI18N
        contact_gokarna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_gokarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_gokarnaActionPerformed(evt);
            }
        });

        directions_gokarna.setBackground(new java.awt.Color(255, 255, 255));
        directions_gokarna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        directions_gokarna.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_gokarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_gokarnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_gokarnaLayout = new javax.swing.GroupLayout(panel_gokarna);
        panel_gokarna.setLayout(panel_gokarnaLayout);
        panel_gokarnaLayout.setHorizontalGroup(
            panel_gokarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gokarnaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_gokarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_gokarnaLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(img_mulberry2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(panel_gokarnaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(directions_gokarna)
                        .addGap(29, 29, 29)
                        .addComponent(contact_gokarna)
                        .addGap(80, 80, 80))))
        );
        panel_gokarnaLayout.setVerticalGroup(
            panel_gokarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_gokarnaLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(img_mulberry2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_gokarnaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contact_gokarna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directions_gokarna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_nepalaya.setBackground(new java.awt.Color(255, 255, 255));
        panel_nepalaya.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HOTEL NEPALAYA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        contact_nepalaya.setBackground(new java.awt.Color(255, 255, 255));
        contact_nepalaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/call.png"))); // NOI18N
        contact_nepalaya.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_nepalaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_nepalayaActionPerformed(evt);
            }
        });

        directions_nepalaya.setBackground(new java.awt.Color(255, 255, 255));
        directions_nepalaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/location.png"))); // NOI18N
        directions_nepalaya.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_nepalaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_nepalayaActionPerformed(evt);
            }
        });

        img_shanker2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_shanker2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hotelnepalaya1.jpg"))); // NOI18N

        javax.swing.GroupLayout panel_nepalayaLayout = new javax.swing.GroupLayout(panel_nepalaya);
        panel_nepalaya.setLayout(panel_nepalayaLayout);
        panel_nepalayaLayout.setHorizontalGroup(
            panel_nepalayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nepalayaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_nepalayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_nepalayaLayout.createSequentialGroup()
                        .addComponent(img_shanker2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(panel_nepalayaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(directions_nepalaya)
                        .addGap(27, 27, 27)
                        .addComponent(contact_nepalaya)
                        .addGap(88, 88, 88))))
        );
        panel_nepalayaLayout.setVerticalGroup(
            panel_nepalayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nepalayaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img_shanker2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panel_nepalayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(directions_nepalaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contact_nepalaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OtherHotel.setText("Other Hotels");
        OtherHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherHotelActionPerformed(evt);
            }
        });

        panel_haze.setBackground(new java.awt.Color(255, 255, 255));
        panel_haze.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PURPLE HAZE ROCK BAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_annapurna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_annapurna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/haze.jpg"))); // NOI18N

        directions_haze.setBackground(new java.awt.Color(255, 255, 255));
        directions_haze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_haze.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_haze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_hazeActionPerformed(evt);
            }
        });

        contact_haze.setBackground(new java.awt.Color(255, 255, 255));
        contact_haze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_haze.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_haze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_hazecontact_boutiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_hazeLayout = new javax.swing.GroupLayout(panel_haze);
        panel_haze.setLayout(panel_hazeLayout);
        panel_hazeLayout.setHorizontalGroup(
            panel_hazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_hazeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(directions_haze)
                .addGap(52, 52, 52)
                .addComponent(contact_haze)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(panel_hazeLayout.createSequentialGroup()
                .addComponent(img_annapurna, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_hazeLayout.setVerticalGroup(
            panel_hazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hazeLayout.createSequentialGroup()
                .addComponent(img_annapurna, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_hazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_hazeLayout.createSequentialGroup()
                        .addComponent(directions_haze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(panel_hazeLayout.createSequentialGroup()
                        .addComponent(contact_haze)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panel_irish2.setBackground(new java.awt.Color(255, 255, 255));
        panel_irish2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IRISH PUB", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 0, 12))); // NOI18N

        img_annapurna4.setBackground(new java.awt.Color(255, 255, 255));
        img_annapurna4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_annapurna4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Irish-Pub-Nepal.jpg"))); // NOI18N

        directions_irish2.setBackground(new java.awt.Color(255, 255, 255));
        directions_irish2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/map.png"))); // NOI18N
        directions_irish2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        directions_irish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directions_irish2ActionPerformed(evt);
            }
        });

        contact_irish2.setBackground(new java.awt.Color(255, 255, 255));
        contact_irish2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contactlogo.png"))); // NOI18N
        contact_irish2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact_irish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_irish2contact_boutiqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_irish2Layout = new javax.swing.GroupLayout(panel_irish2);
        panel_irish2.setLayout(panel_irish2Layout);
        panel_irish2Layout.setHorizontalGroup(
            panel_irish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_irish2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_irish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_irish2Layout.createSequentialGroup()
                        .addComponent(img_annapurna4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_irish2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(directions_irish2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contact_irish2)
                        .addGap(84, 84, 84))))
        );
        panel_irish2Layout.setVerticalGroup(
            panel_irish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_irish2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(img_annapurna4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_irish2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact_irish2)
                    .addComponent(directions_irish2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        OtherNightlife.setText("Other Places");
        OtherNightlife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtherNightlifeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_annapurna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_gokarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_dwarika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_nepalaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_irish2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_haze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(OtherHotel)
                        .addGap(715, 715, 715)
                        .addComponent(OtherNightlife)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panel_haze, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel_dwarika, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_annapurna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel_nepalaya, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_gokarna, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(panel_irish2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OtherNightlife)
                    .addComponent(OtherHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void directions_annapurnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_annapurnaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//hotel+annapurna+kathmandu/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39eb19017fa3b0cf:0xd988bc5b5c01f9df?sa=X&ved=2ahUKEwiHhab248D1AhVCw4sBHSiMCA0Q9Rd6BAg5EAM").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_annapurnaActionPerformed

    private void contact_annapurnacontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_annapurnacontact_boutiqueActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://del-annapurna-hotel-kathmandu.at-hotels.com/en/").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_contact_annapurnacontact_boutiqueActionPerformed

    private void contact_dwarikacontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_dwarikacontact_boutiqueActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.dwarikas.com/home/").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_contact_dwarikacontact_boutiqueActionPerformed

    private void directions_dwarikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_dwarikaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//the+dwarika+hotel/data=!4m6!4m5!1m1!4e2!1m2!1m1!1s0x39eb199d62b49797:0x2138d3ae677c130f?sa=X&hl=en&ved=2ahUKEwip2tPr5sD1AhUdTmwGHa7EBNgQ9Rd6BAghEAQ").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_dwarikaActionPerformed

    private void contact_gokarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_gokarnaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("http://www.mulberrynepal.com/contact-us/").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_contact_gokarnaActionPerformed

    private void directions_gokarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_gokarnaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/27.7179392,85.3446312/Hotel+Mulberry,+Jyatha+Galli,+Kathmandu/@27.7177627,85.3196827,15z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb18fd8c5c03ed:0x560379d6ad5bc91d!2m2!1d85.3132375!2d27.7126449").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_gokarnaActionPerformed

    private void contact_nepalayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_nepalayaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.hotelnepalaya.com/").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_contact_nepalayaActionPerformed

    private void directions_nepalayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_nepalayaActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/27.7179392,85.3446312/hotel+nepalaya/@27.713376,85.3104263,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb18fc2c472d21:0xe9bfbc07f792977e!2m2!1d85.311406!2d27.7121088?hl=en").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_nepalayaActionPerformed

    private void OtherHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherHotelActionPerformed
        new OtherHotel().setVisible(true);
    }//GEN-LAST:event_OtherHotelActionPerformed

    private void directions_hazeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_hazeActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Purple+Haze+Rock+Bar/@27.7147936,85.3083373,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb18fce452e207:0x70be89a8c5e4fce3!8m2!3d27.7147834!4d85.3105231?hl=en").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_hazeActionPerformed

    private void contact_hazecontact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_hazecontact_boutiqueActionPerformed
        new HazeDetails().setVisible(true);
    }//GEN-LAST:event_contact_hazecontact_boutiqueActionPerformed

    private void directions_irish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directions_irish2ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/27.7250048,85.3409792/irish+pub+lazimpat/@27.72501,85.311641,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x39eb191cbf0fe1a1:0x374d4d3d31aa83ce!2m2!1d85.3175481!2d27.7184685").toURI());
        }
        catch(Exception e){}
    }//GEN-LAST:event_directions_irish2ActionPerformed

    private void contact_irish2contact_boutiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_irish2contact_boutiqueActionPerformed
        new IrishDetails().setVisible(true);
    }//GEN-LAST:event_contact_irish2contact_boutiqueActionPerformed

    private void OtherNightlifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtherNightlifeActionPerformed
        // TODO add your handling code here:
        new OtherNightlife().setVisible(true);
    }//GEN-LAST:event_OtherNightlifeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OtherHotel;
    private javax.swing.JButton OtherNightlife;
    private javax.swing.JButton contact_annapurna;
    private javax.swing.JButton contact_dwarika;
    private javax.swing.JButton contact_gokarna;
    private javax.swing.JButton contact_haze;
    private javax.swing.JButton contact_irish2;
    private javax.swing.JButton contact_nepalaya;
    private javax.swing.JButton directions_annapurna;
    private javax.swing.JButton directions_dwarika;
    private javax.swing.JButton directions_gokarna;
    private javax.swing.JButton directions_haze;
    private javax.swing.JButton directions_irish2;
    private javax.swing.JButton directions_nepalaya;
    private javax.swing.JLabel img_annapurna;
    private javax.swing.JLabel img_annapurna4;
    private javax.swing.JLabel img_boutique1;
    private javax.swing.JLabel img_mariott1;
    private javax.swing.JLabel img_mulberry2;
    private javax.swing.JLabel img_shanker2;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_annapurna;
    private javax.swing.JPanel panel_dwarika;
    private javax.swing.JPanel panel_gokarna;
    private javax.swing.JPanel panel_haze;
    private javax.swing.JPanel panel_irish2;
    private javax.swing.JPanel panel_nepalaya;
    // End of variables declaration//GEN-END:variables
}
