package view;

import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class Restaurant extends javax.swing.JInternalFrame {

    public Restaurant() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null); 
        getContentPane().setBackground(Color.white);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        utpalaContact = new javax.swing.JButton();
        utpalaMap = new javax.swing.JButton();
        utpalaSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        spizeSave = new javax.swing.JButton();
        spizeContact = new javax.swing.JButton();
        spizeMap = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        nepalayaSave = new javax.swing.JButton();
        nepalayaContact = new javax.swing.JButton();
        nepalayaMap = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        upstairMap = new javax.swing.JButton();
        upstairContact = new javax.swing.JButton();
        upstairSave = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        marcoMap = new javax.swing.JButton();
        marcoContact = new javax.swing.JButton();
        marcoSave = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        frenchMap = new javax.swing.JButton();
        frenchContact = new javax.swing.JButton();
        frenchSave = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        otherRes = new javax.swing.JButton();

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel21.setText("Himalayan Java");

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel23.setText("Roadhouse Cafe");

        jLabel25.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel25.setText("Roadhouse Cafe");

        jLabel26.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel26.setText("K-Too Beer & Steak House");

        jLabel27.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel27.setText("K-Too Beer & Steak House");

        jLabel52.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel52.setText("Peroz Pizza ");

        jLabel54.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel54.setText("KFC ");

        jLabel55.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel55.setText("KFC ");

        jLabel56.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel56.setText("Peroz Pizza ");

        jLabel57.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel57.setText("Peroz Pizza ");

        jLabel58.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel58.setText("KFC ");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 245, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Utpala Cafe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/utpala.jpg"))); // NOI18N

        utpalaContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        utpalaContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utpalaContactActionPerformed(evt);
            }
        });

        utpalaMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        utpalaMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utpalaMapActionPerformed(evt);
            }
        });

        utpalaSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        utpalaSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utpalaSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(utpalaMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(utpalaContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(utpalaSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utpalaContact)
                    .addComponent(utpalaMap)
                    .addComponent(utpalaSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 245, 238));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Spize", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spiz.jpeg"))); // NOI18N

        spizeSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        spizeSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spizeSaveActionPerformed(evt);
            }
        });

        spizeContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        spizeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spizeContactActionPerformed(evt);
            }
        });

        spizeMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        spizeMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spizeMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(spizeMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(spizeContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(spizeSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(spizeMap))
                    .addComponent(spizeSave)
                    .addComponent(spizeContact))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 245, 238));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nepalaya Rooftop", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nepalaya.png"))); // NOI18N

        nepalayaSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        nepalayaSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nepalayaSaveActionPerformed(evt);
            }
        });

        nepalayaContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        nepalayaContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nepalayaContactActionPerformed(evt);
            }
        });

        nepalayaMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        nepalayaMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nepalayaMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nepalayaMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nepalayaContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(nepalayaSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nepalayaSave)
                    .addComponent(nepalayaContact)
                    .addComponent(nepalayaMap))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 245, 238));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Upstairs Cafe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upsta.png"))); // NOI18N

        upstairMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        upstairMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upstairMapActionPerformed(evt);
            }
        });

        upstairContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        upstairContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upstairContactActionPerformed(evt);
            }
        });

        upstairSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        upstairSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upstairSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(upstairMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(upstairContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(upstairSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel33)
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upstairMap)
                    .addComponent(upstairContact)
                    .addComponent(upstairSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 245, 238));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marcopolo Restaurant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcopoloLogo.png"))); // NOI18N

        marcoMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        marcoMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoMapActionPerformed(evt);
            }
        });

        marcoContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        marcoContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoContactActionPerformed(evt);
            }
        });

        marcoSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        marcoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcoSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(marcoMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(marcoContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(marcoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcoMap)
                    .addComponent(marcoContact)
                    .addComponent(marcoSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 245, 238));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "French creperie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/french.jpeg"))); // NOI18N

        frenchMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/map.png"))); // NOI18N
        frenchMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchMapActionPerformed(evt);
            }
        });

        frenchContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contactlogo.png"))); // NOI18N
        frenchContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchContactActionPerformed(evt);
            }
        });

        frenchSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/savee.png"))); // NOI18N
        frenchSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(frenchMap, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(frenchContact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(frenchSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frenchSave, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(frenchMap, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(frenchContact)))
                .addGap(44, 44, 44))
        );

        jLabel51.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 69, 0));
        jLabel51.setText("Popular Restaurants");

        otherRes.setText("Other Restaurants");
        otherRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherResActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 254, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(otherRes)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherRes)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1244, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utpalaContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utpalaContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: 9810700763 \n"+"Email: utpalacafeboudha@gmail.com \nLocation: Utpala Way , Road, Kathmandu 44600, 44600", "Contacts", JOptionPane.PLAIN_MESSAGE);
        // TODO add your handling code here:
    }//GEN-LAST:event_utpalaContactActionPerformed

    private void utpalaMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utpalaMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/place/Utpala+Caf%C3%A9/@27.7243241,85.3601154,17z/data=!3m1!4b1!4m5!3m4!1s0x39eb1becafc4f609:0x38051dfc15e69cbf!8m2!3d27.7243241!4d85.3623041").toURI());
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_utpalaMapActionPerformed

    private void utpalaSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utpalaSaveActionPerformed
        JOptionPane.showMessageDialog(null, "Utpala is an all-day-restaurant that offers a fresh vegetarian menu that is healthy, \n"
            + " inexpensive and tasty respecting our origins of being a Monastery Restaurant ","Details",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_utpalaSaveActionPerformed

    private void spizeSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spizeSaveActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, " Spize is located in Thamel, dedicated to providing cheap, delicious and hygienic food to its guests. \n"
            + " We serve traditional Nepali and travellers food using Himalayan spices to flavour up your meal.","Details",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_spizeSaveActionPerformed

    private void spizeContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spizeContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: 01-4413730 \n"+"Email: spize.thamel@gmail.com \nLocation: Bhagwati Marg, Kathmandu 44600", "Contacts", JOptionPane.PLAIN_MESSAGE);
       
    }//GEN-LAST:event_spizeContactActionPerformed

    private void spizeMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spizeMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/Spize,+Bhagwati+Marg,+Kathmandu+44600//@27.7161101,85.276166,13z/data=!3m1!4b1!4m8!4m7!1m5!1m1!1s0x39eb18fd286e0df9:0x87fe5006f0e263ad!2m2!1d85.3111671!2d27.7160496!1m0").toURI());
        }
        catch(Exception e){
        }       
    }//GEN-LAST:event_spizeMapActionPerformed

    private void nepalayaSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nepalayaSaveActionPerformed
        JOptionPane.showMessageDialog(null, " Nepalaya rooftop restaurant is complete vegetarian, vegan, yoga /Ayurveda restaurant.\n"
           
            + "  One who is searching for vegetarian and vegan food this might be the best choice.","Details",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_nepalayaSaveActionPerformed

    private void nepalayaContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nepalayaContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: 01-5901321 \n"+"Email:  hnepalaya@gmail.com \n"+"Location:Kwabahal-17 Inside Hotel Nepalaya, Kathmandu 44600 ", "Contacts", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_nepalayaContactActionPerformed

    private void nepalayaMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nepalayaMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir/Nepalaya+Rooftop+Restaurant,+Kathmandu//@27.7120949,85.2763831,13z/data=!4m8!4m7!1m5!1m1!1s0x39eb1928b963e0d1:0xecbfbd14d4d2bc16!2m2!1d85.3114026!2d27.7120993!1m0").toURI());
        }
        catch(Exception e){
        }        
    }//GEN-LAST:event_nepalayaMapActionPerformed

    private void upstairMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upstairMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//Upstairs,+Kathmandu/@27.7030335,85.2726487,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x39eb18566e50bd01:0xc3445f195be7c11e!2m2!1d85.3076474!2d27.7030368").toURI());
        }
        catch(Exception e){
        }        
    }//GEN-LAST:event_upstairMapActionPerformed

    private void upstairContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upstairContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: +977 1-4700035 \n"+"Email: upstairscafektm@gmail.com \nLocation: Chaksibari marg Thamel Kathmandu Kathmandu, Nepal", "Contacts", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_upstairContactActionPerformed

    private void upstairSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upstairSaveActionPerformed
        JOptionPane.showMessageDialog(null, "Its a new restaurant in thamel where you can get quality product in reasonable price","Details",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_upstairSaveActionPerformed

    private void marcoMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcoMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//marcopolo+restaurants/@27.7153915,85.278132,13z/data=!4m8!4m7!1m0!1m5!1m1!1s0x39eb1962b8075ec9:0x3bca112cd70e43df!2m2!1d85.3131515!2d27.7153959").toURI());
        }
        catch(Exception e){
        }        
    }//GEN-LAST:event_marcoMapActionPerformed

    private void marcoContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcoContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: 01-5252282 \n"+"Email: marcopolo@smartlyyours.com \nLocation: 1st Floor, Chhaya Center, Kathmandu", "Contacts", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_marcoContactActionPerformed

    private void marcoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcoSaveActionPerformed
        JOptionPane.showMessageDialog(null, "Marcopolo restaurant was established under the sole initiation of Rubiolo Battista,\n"
            + " an aspiring Italian Chef, back in 1987.","Details",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_marcoSaveActionPerformed

    private void frenchMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchMapActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.google.com/maps/dir//French+Creperie+Kathmandu,+Thamel+Marg,+Kathmandu/@27.7132876,85.2763135,13z/data=!3m1!4b1!4m8!4m7!1m0!1m5!1m1!1s0x39eb1981dfb50ac1:0x20d624f9e7a6d179!2m2!1d85.311333!2d27.713292").toURI());
        }
        catch(Exception e){
        }        
    }//GEN-LAST:event_frenchMapActionPerformed

    private void frenchContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchContactActionPerformed
        JOptionPane.showMessageDialog(null, "Phone No: +977 984-3339062 \n"+"Email: frenchcreperiektm@gmail.com \nLocation:  Thamel Marg 26, Kathmandu 44600", "Contacts", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_frenchContactActionPerformed

    private void frenchSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchSaveActionPerformed
 
        JOptionPane.showMessageDialog(null, "The french creperie serve typical french food.\n"
            + "French restaurant : galettes, crêpes, raclette, croque monsieur, cheese. Vegan and vegetarian friendly.","Details",JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_frenchSaveActionPerformed

    private void otherResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherResActionPerformed
        // TODO add your handling code here:
        new OtherRestaurants().setVisible(true);
    }//GEN-LAST:event_otherResActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton frenchContact;
    private javax.swing.JButton frenchMap;
    private javax.swing.JButton frenchSave;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton marcoContact;
    private javax.swing.JButton marcoMap;
    private javax.swing.JButton marcoSave;
    private javax.swing.JButton nepalayaContact;
    private javax.swing.JButton nepalayaMap;
    private javax.swing.JButton nepalayaSave;
    private javax.swing.JButton otherRes;
    private javax.swing.JButton spizeContact;
    private javax.swing.JButton spizeMap;
    private javax.swing.JButton spizeSave;
    private javax.swing.JButton upstairContact;
    private javax.swing.JButton upstairMap;
    private javax.swing.JButton upstairSave;
    private javax.swing.JButton utpalaContact;
    private javax.swing.JButton utpalaMap;
    private javax.swing.JButton utpalaSave;
    // End of variables declaration//GEN-END:variables
}
